version: '3.7'

services:
  postgres:
    build: './service'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: myPassword
      POSTGRES_DB: mydb
    restart: always

  nats:
    image: 'nats-streaming:0.9.2'
    restart: always