version: "3.7"

services:
  postgres:
    build: "./service"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: myPassword
      POSTGRES_DB: mydb
    restart: always

  nats:
    image: "nats-streaming:0.9.2"
    restart: always
  
  elastic:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.17.8"
    environment:
      - "discovery.type=single-node"

  feed:
    build: "."
    command: "cmd-feed"
    depends_on:
      - "postgres"
      - "nats"
    ports:
      - "8080"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: myPassword
      POSTGRES_DB: mydb
      NATS_ADDRESS: "nats:4222"
  
  query:
    build: "."
    command: "cmd-search"
    depends_on:
      - "postgres"
      - "nats"
      - "elastic"
    ports:
      - "8080"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: myPassword
      POSTGRES_DB: mydb
      NATS_ADDRESS: "nats:4222"
      ELASTCISEARCH_ADDRESS: "elasticsearch:9200"

  pusher:
    build: "."
    command: "cmd-pusher"
    depends_on:
      - "nats"
    ports:
      - "8080"
    environment:
      NATS_ADDRESS: "nats:4222"

  nginx:
    build: "./nginx"
    ports:
      - "8080:80"
    depends_on:
      - "feed"
      - "query"
      - "pusher"
