version: 3.7

services:
  postgres:
    build: ./service
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: myPassword
      POSTGRES_DB: mydb
    restart: always

  nats:
    image: nats-streaming:0.9.2
    restart: always
  
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.3
    environment:
      - dicovery.type=single-node

  feed:
    build: .
    command: feed-service
    depends_on:
      - postgres
      - nats
    ports:
      - 8080
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: myPassword
      POSTGRES_DB: mydb
      NATS_ADDRESS: nats:4222
